import {useState,useEffect} from 'react';
import {cashOperation} from '../api';
const methods={dinheiro:'Dinheiro',pix:'PIX',debito:'Débito',credito:'Crédito'};
const money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function CashShift({onClose}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[opening,setOpening]=useState('0'),[kind,setKind]=useState('suprimento'),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[counted,setCounted]=useState({dinheiro:'',pix:'',debito:'',credito:''}),[notice,setNotice]=useState('');
 const load=()=>cashOperation('shift').then(setData).catch(e=>setError(e.message));useEffect(()=>{void load();},[]);
 const act=async(path,body)=>{if(busy)return;setBusy(true);setError('');try{await cashOperation(path,body);setNotice('Operação registrada.');setAmount('');setReason('');await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <div className="payment-backdrop"><section className="payment-dialog" role="dialog" aria-modal="true" aria-label="Turno do caixa"><header><h2>Turno do caixa</h2><button className="btn btn-secondary" onClick={onClose}>Fechar</button></header><div className="payment-body">{error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data?<p>Carregando…</p>:!data.current?<><h3>Abrir turno</h3><label>Dinheiro inicial<input type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)}/></label><button className="btn btn-primary" disabled={busy} onClick={()=>act('shift',{opening})}>Abrir turno</button></>:<><h3>Turno #{data.current.id}</h3><p>Aberto em {data.current.opened_at}. Recebimentos registrados sem turno não entram nesta conferência.</p><h3>Conferência por meio</h3>{Object.entries(methods).map(([m,label])=><label className="payment-item" key={m}><span>{label}<small>Esperado: {money(data.current.expected[m])}</small></span><input aria-label={'Conferido em '+label} type="number" min="0" step="0.01" value={counted[m]} onChange={e=>setCounted({...counted,[m]:e.target.value})}/><small>{counted[m]!==''?'Diferença: '+money(Math.round(Number(counted[m])*100)-data.current.expected[m]):'Não conferido'}</small></label>)}<button className="btn btn-primary" disabled={busy||Object.values(counted).some(v=>v==='')} onClick={()=>act('shift/close',{counted})}>Concluir conferência e fechar turno</button><h3>Movimentar dinheiro</h3><div className="payment-tender"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="suprimento">Suprimento</option><option value="sangria">Sangria</option></select><input aria-label="Valor da movimentação" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><input aria-label="Motivo" placeholder="Motivo da movimentação" value={reason} onChange={e=>setReason(e.target.value)}/><button className="btn btn-secondary" disabled={busy} onClick={()=>act('movement',{kind,amount,reason})}>Registrar movimentação</button>{data.current.movements.map(m=><p key={m.id}>{m.kind} · {money(m.amount_cents)} · {m.reason}</p>)}</>}
 <h3>Últimos fechamentos</h3>{data?.history.map(s=><details key={s.id}><summary>Turno #{s.id} · {s.closed_at}</summary>{Object.entries(JSON.parse(s.closing_json).difference).map(([m,n])=><p key={m}>{methods[m]}: diferença {money(n)}</p>)}</details>)}</div></section></div>;
}
